name: .NET Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        fetch-depth: 0

    # 安装 .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: '6.0.x'
        
    # 安装 NuGet
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      with:
        nuget-version: '5.x'

    # 还原 NuGet 包
    - name: NuGet restore
      run: nuget restore
      
    # 添加 MSBuild.exe 到环境变量: https://github.com/microsoft/setup-msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    # 编译项目 (Release 版本)
    - name: Build Any CPU
      run: |
        msbuild "Ink Canvas/Ink Canvas.csproj" /p:Configuration=Release /p:Platform="Any CPU" /p:GitFlow="Github Action" /p:AllowUnsafeBlocks=true
      env:
        Configuration: ${{ matrix.configuration }}
    
    - name: Build x64
      run: |
        msbuild "Ink Canvas/Ink Canvas.csproj" /p:Configuration=Release /p:Platform=x64 /p:GitFlow="Github Action" /p:AllowUnsafeBlocks=true
      env:
        Configuration: ${{ matrix.configuration }}
    
    - name: Build ARM64
      run: |
        msbuild "Ink Canvas/Ink Canvas.csproj" /p:Configuration=Release /p:Platform=ARM64 /p:GitFlow="Github Action" /p:AllowUnsafeBlocks=true
      env:
        Configuration: ${{ matrix.configuration }}

    # 上传编译成品
    - name: Upload Any CPU
      uses: actions/upload-artifact@main
      with:
        name: Ink Canvas Pro (Any CPU)
        path: Ink Canvas/bin/Any CPU/Release
        
    - name: Upload x64
      uses: actions/upload-artifact@main
      with:
        name: Ink Canvas Pro (x64)
        path: Ink Canvas/bin/x64/Release
        
    - name: Upload ARM64
      uses: actions/upload-artifact@main
      with:
        name: Ink Canvas Pro (ARM64)
        path: Ink Canvas/bin/ARM64/Release
        
    # 安装 Inno Setup
    - name: Install Inno Setup
      run: |
        choco install innosetup -y
      shell: pwsh

    # 使用 Inno Setup 打包 (我们已经修改了脚本使用正确的路径)
    - name: Build installers
      run: |
        iscc ".github\workflows\Ink Canvas Pro-x64.iss"
        iscc ".github\workflows\Ink Canvas Pro-ARM64.iss"
        iscc ".github\workflows\Ink Canvas Pro-AnyCPU.iss"
      shell: pwsh

    # 上传安装包
    - name: Upload installers
      uses: actions/upload-artifact@main
      with:
        name: Ink Canvas Pro Installers
        path: Release\*.exe